#!/usr/bin/env python
# coding: utf-8

#  Link for FITS image download: https://dr12.sdss.org/fields/name?name=M42
#  Directory location: D:\Astrophysics Coding\Python for Astronomy\FITS files



import numpy as np
import matplotlib.pyplot as plt



from astropy.io import fits


# Now we are ready to load some FITS files and analize them.

M42 = fits.open('frame-u-006073-4-0063.fits.bz2')

M42


M42.info()



M42[0]   #we choosed 0=primary file because it contains our imp Image.


M42[0].header


M42[1].header


data = M42[0].data



data



type(data)



data.shape   # it is generally the pixel of the image.



print('Min:', np.min(data))
print('Max:', np.max(data))
print('Mean:', np.mean(data))
print('Stdev:', np.std(data))


plt.imshow(data , cmap='gray')  # here we use imshow because we have a 2-D/3-D array(we cannot apply plt.plot for 2-D array).
plt.colorbar()


Histogram = plt.hist(data.flat , bins=500)


from matplotlib.colors import LogNorm

plt.imshow(data , cmap='gray' , norm=LogNorm())
cbar = plt.colorbar(ticks=[5.e3,1.e4,2.e4])
cbar.a.set_yticklabels(['5000' , '10,000' , '20,000'])


# Our aim to plot rgb image which will help us to analysis and produce a productive data of M42.


from astropy.visualization import make_lupton_rgb


M42u=fits.open('frame-u-006073-4-0063.fits.bz2')
M42i=fits.open('frame-i-006073-4-0063.fits.bz2')
M42g=fits.open('frame-g-006073-4-0063.fits.bz2')



u=M42u[0].data
i=M42i[0].data
g=M42g[0].data



rgb_default = make_lupton_rgb(i , g , u, stretch=1.5 , Q=10)  #here, i=r , g=g and u=b and are arranged acc to their wavelength which this gives us a proper result to observe our data.
                                                              # stretch = amount of pixel. More the value greater the quality of image.

plt.imshow(rgb_default , origin='lower')
plt.savefig("rgbM42.jpg")



rgb_default = make_lupton_rgb(g , u , i, stretch=1.5 , Q=10)

plt.imshow(rgb_default , origin='lower')
plt.savefig("rgb1M42.jpg")




rgb_default = make_lupton_rgb(u , i , g, stretch=1.5 , Q=10)

plt.imshow(rgb_default , origin='lower')
plt.savefig("rgb2M42.jpg")


# # Units and Co-ordinates

from astropy import units as u
from astropy.coordinates import SkyCoord



c= SkyCoord(ra=10.625*u.degree, dec=41.2*u.degree)
c= SkyCoord(10.625, 41.2, unit='degree')
c= SkyCoord('00h42m30s' , '+41d12m00s')
c= SkyCoord('00h42.5m' , '+41d12m')
c= SkyCoord('00 42 30 +41 12 00' , unit=(u.hourangle, u.deg))
c= SkyCoord('00:42.5 +41:12' , unit=(u.hourangle, u.deg))
c

c.ra

c.ra.hour


# In[46]:


c.galactic


c.dec


# In[49]:


c.dec.radian


c.transform_to('fk5')

